//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTableProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public int user_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string accountno { get; set; }
        public string cardtype { get; set; }
        public Nullable<bool> feespaid { get; set; }
        public byte[] document { get; set; }
    }
}
